// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testM.proto
package test;

import com.wzjwhut.protoc.Main;
import com.wzjwhut.util.text.HexUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import test.MyProtoOuterClass.MyProto;
import test.MyProtoOuterClass.MyType;

public class TestMyProto{
    private final static Logger logger = LogManager.getLogger(Main.class);

    public static void main(String[] args) throws Throwable{
        MyType.Builder mytype = MyType.newBuilder();
        MyProto.Builder myproto = MyProto.newBuilder();
        mytype.setI32(123);

        myproto.setI32(456);
        myproto.setI64(789);
        myproto.setStr("hello");
        myproto.setMsg(mytype);
        byte[] out = myproto.build().toByteArray();
        logger.info("out: {}", HexUtils.dumpString(out));
    }
}
