// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyProto.proto

package test;

public final class MyProtoOuterClass {
  private MyProtoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.MyType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 i32 = 1;</code>
     */
    boolean hasI32();
    /**
     * <code>optional int32 i32 = 1;</code>
     */
    int getI32();
  }
  /**
   * Protobuf type {@code test.MyType}
   */
  public  static final class MyType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.MyType)
      MyTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyType.newBuilder() to construct.
    private MyType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyType() {
      i32_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              i32_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.MyProtoOuterClass.internal_static_test_MyType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.MyProtoOuterClass.internal_static_test_MyType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.MyProtoOuterClass.MyType.class, test.MyProtoOuterClass.MyType.Builder.class);
    }

    private int bitField0_;
    public static final int I32_FIELD_NUMBER = 1;
    private int i32_;
    /**
     * <code>optional int32 i32 = 1;</code>
     */
    public boolean hasI32() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 i32 = 1;</code>
     */
    public int getI32() {
      return i32_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, i32_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i32_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.MyProtoOuterClass.MyType)) {
        return super.equals(obj);
      }
      test.MyProtoOuterClass.MyType other = (test.MyProtoOuterClass.MyType) obj;

      boolean result = true;
      result = result && (hasI32() == other.hasI32());
      if (hasI32()) {
        result = result && (getI32()
            == other.getI32());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasI32()) {
        hash = (37 * hash) + I32_FIELD_NUMBER;
        hash = (53 * hash) + getI32();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.MyProtoOuterClass.MyType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.MyProtoOuterClass.MyType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.MyProtoOuterClass.MyType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.MyProtoOuterClass.MyType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.MyType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.MyType)
        test.MyProtoOuterClass.MyTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.MyProtoOuterClass.internal_static_test_MyType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.MyProtoOuterClass.internal_static_test_MyType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.MyProtoOuterClass.MyType.class, test.MyProtoOuterClass.MyType.Builder.class);
      }

      // Construct using test.MyProtoOuterClass.MyType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        i32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.MyProtoOuterClass.internal_static_test_MyType_descriptor;
      }

      @java.lang.Override
      public test.MyProtoOuterClass.MyType getDefaultInstanceForType() {
        return test.MyProtoOuterClass.MyType.getDefaultInstance();
      }

      @java.lang.Override
      public test.MyProtoOuterClass.MyType build() {
        test.MyProtoOuterClass.MyType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.MyProtoOuterClass.MyType buildPartial() {
        test.MyProtoOuterClass.MyType result = new test.MyProtoOuterClass.MyType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.i32_ = i32_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.MyProtoOuterClass.MyType) {
          return mergeFrom((test.MyProtoOuterClass.MyType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.MyProtoOuterClass.MyType other) {
        if (other == test.MyProtoOuterClass.MyType.getDefaultInstance()) return this;
        if (other.hasI32()) {
          setI32(other.getI32());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.MyProtoOuterClass.MyType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.MyProtoOuterClass.MyType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int i32_ ;
      /**
       * <code>optional int32 i32 = 1;</code>
       */
      public boolean hasI32() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 i32 = 1;</code>
       */
      public int getI32() {
        return i32_;
      }
      /**
       * <code>optional int32 i32 = 1;</code>
       */
      public Builder setI32(int value) {
        bitField0_ |= 0x00000001;
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 i32 = 1;</code>
       */
      public Builder clearI32() {
        bitField0_ = (bitField0_ & ~0x00000001);
        i32_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.MyType)
    }

    // @@protoc_insertion_point(class_scope:test.MyType)
    private static final test.MyProtoOuterClass.MyType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.MyProtoOuterClass.MyType();
    }

    public static test.MyProtoOuterClass.MyType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyType>
        PARSER = new com.google.protobuf.AbstractParser<MyType>() {
      @java.lang.Override
      public MyType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.MyProtoOuterClass.MyType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MyProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.MyProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .test.MyProto.MessageType message_type = 12;</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .test.MyProto.MessageType message_type = 12;</code>
     */
    test.MyProtoOuterClass.MyProto.MessageType getMessageType();

    /**
     * <code>optional string str = 1 [default = "hello world"];</code>
     */
    boolean hasStr();
    /**
     * <code>optional string str = 1 [default = "hello world"];</code>
     */
    java.lang.String getStr();
    /**
     * <code>optional string str = 1 [default = "hello world"];</code>
     */
    com.google.protobuf.ByteString
        getStrBytes();

    /**
     * <code>optional int32 i32 = 2;</code>
     */
    boolean hasI32();
    /**
     * <code>optional int32 i32 = 2;</code>
     */
    int getI32();

    /**
     * <code>optional int64 i64 = 3;</code>
     */
    boolean hasI64();
    /**
     * <code>optional int64 i64 = 3;</code>
     */
    long getI64();

    /**
     * <code>optional .test.MyType msg = 4;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional .test.MyType msg = 4;</code>
     */
    test.MyProtoOuterClass.MyType getMsg();
    /**
     * <code>optional .test.MyType msg = 4;</code>
     */
    test.MyProtoOuterClass.MyTypeOrBuilder getMsgOrBuilder();
  }
  /**
   * Protobuf type {@code test.MyProto}
   */
  public  static final class MyProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.MyProto)
      MyProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyProto.newBuilder() to construct.
    private MyProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyProto() {
      messageType_ = 1;
      str_ = "hello world";
      i32_ = 0;
      i64_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              str_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000004;
              i32_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000008;
              i64_ = input.readInt64();
              break;
            }
            case 34: {
              test.MyProtoOuterClass.MyType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(test.MyProtoOuterClass.MyType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 96: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              test.MyProtoOuterClass.MyProto.MessageType value = test.MyProtoOuterClass.MyProto.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(12, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.MyProtoOuterClass.internal_static_test_MyProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.MyProtoOuterClass.internal_static_test_MyProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.MyProtoOuterClass.MyProto.class, test.MyProtoOuterClass.MyProto.Builder.class);
    }

    /**
     * Protobuf enum {@code test.MyProto.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TYPE1 = 1;</code>
       */
      TYPE1(1),
      /**
       * <code>TYPE2 = 2;</code>
       */
      TYPE2(2),
      ;

      /**
       * <code>TYPE1 = 1;</code>
       */
      public static final int TYPE1_VALUE = 1;
      /**
       * <code>TYPE2 = 2;</code>
       */
      public static final int TYPE2_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 1: return TYPE1;
          case 2: return TYPE2;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return test.MyProtoOuterClass.MyProto.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:test.MyProto.MessageType)
    }

    private int bitField0_;
    public static final int MESSAGE_TYPE_FIELD_NUMBER = 12;
    private int messageType_;
    /**
     * <code>optional .test.MyProto.MessageType message_type = 12;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .test.MyProto.MessageType message_type = 12;</code>
     */
    public test.MyProtoOuterClass.MyProto.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      test.MyProtoOuterClass.MyProto.MessageType result = test.MyProtoOuterClass.MyProto.MessageType.valueOf(messageType_);
      return result == null ? test.MyProtoOuterClass.MyProto.MessageType.TYPE1 : result;
    }

    public static final int STR_FIELD_NUMBER = 1;
    private volatile java.lang.Object str_;
    /**
     * <code>optional string str = 1 [default = "hello world"];</code>
     */
    public boolean hasStr() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string str = 1 [default = "hello world"];</code>
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          str_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string str = 1 [default = "hello world"];</code>
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int I32_FIELD_NUMBER = 2;
    private int i32_;
    /**
     * <code>optional int32 i32 = 2;</code>
     */
    public boolean hasI32() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 i32 = 2;</code>
     */
    public int getI32() {
      return i32_;
    }

    public static final int I64_FIELD_NUMBER = 3;
    private long i64_;
    /**
     * <code>optional int64 i64 = 3;</code>
     */
    public boolean hasI64() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 i64 = 3;</code>
     */
    public long getI64() {
      return i64_;
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private test.MyProtoOuterClass.MyType msg_;
    /**
     * <code>optional .test.MyType msg = 4;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .test.MyType msg = 4;</code>
     */
    public test.MyProtoOuterClass.MyType getMsg() {
      return msg_ == null ? test.MyProtoOuterClass.MyType.getDefaultInstance() : msg_;
    }
    /**
     * <code>optional .test.MyType msg = 4;</code>
     */
    public test.MyProtoOuterClass.MyTypeOrBuilder getMsgOrBuilder() {
      return msg_ == null ? test.MyProtoOuterClass.MyType.getDefaultInstance() : msg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, str_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(2, i32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(3, i64_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(4, getMsg());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(12, messageType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, str_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, i32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, i64_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMsg());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(12, messageType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.MyProtoOuterClass.MyProto)) {
        return super.equals(obj);
      }
      test.MyProtoOuterClass.MyProto other = (test.MyProtoOuterClass.MyProto) obj;

      boolean result = true;
      result = result && (hasMessageType() == other.hasMessageType());
      if (hasMessageType()) {
        result = result && messageType_ == other.messageType_;
      }
      result = result && (hasStr() == other.hasStr());
      if (hasStr()) {
        result = result && getStr()
            .equals(other.getStr());
      }
      result = result && (hasI32() == other.hasI32());
      if (hasI32()) {
        result = result && (getI32()
            == other.getI32());
      }
      result = result && (hasI64() == other.hasI64());
      if (hasI64()) {
        result = result && (getI64()
            == other.getI64());
      }
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageType()) {
        hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + messageType_;
      }
      if (hasStr()) {
        hash = (37 * hash) + STR_FIELD_NUMBER;
        hash = (53 * hash) + getStr().hashCode();
      }
      if (hasI32()) {
        hash = (37 * hash) + I32_FIELD_NUMBER;
        hash = (53 * hash) + getI32();
      }
      if (hasI64()) {
        hash = (37 * hash) + I64_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getI64());
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.MyProtoOuterClass.MyProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.MyProtoOuterClass.MyProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.MyProtoOuterClass.MyProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.MyProtoOuterClass.MyProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.MyProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.MyProto)
        test.MyProtoOuterClass.MyProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.MyProtoOuterClass.internal_static_test_MyProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.MyProtoOuterClass.internal_static_test_MyProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.MyProtoOuterClass.MyProto.class, test.MyProtoOuterClass.MyProto.Builder.class);
      }

      // Construct using test.MyProtoOuterClass.MyProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMsgFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        str_ = "hello world";
        bitField0_ = (bitField0_ & ~0x00000002);
        i32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        i64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.MyProtoOuterClass.internal_static_test_MyProto_descriptor;
      }

      @java.lang.Override
      public test.MyProtoOuterClass.MyProto getDefaultInstanceForType() {
        return test.MyProtoOuterClass.MyProto.getDefaultInstance();
      }

      @java.lang.Override
      public test.MyProtoOuterClass.MyProto build() {
        test.MyProtoOuterClass.MyProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.MyProtoOuterClass.MyProto buildPartial() {
        test.MyProtoOuterClass.MyProto result = new test.MyProtoOuterClass.MyProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.str_ = str_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.i32_ = i32_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.i64_ = i64_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.MyProtoOuterClass.MyProto) {
          return mergeFrom((test.MyProtoOuterClass.MyProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.MyProtoOuterClass.MyProto other) {
        if (other == test.MyProtoOuterClass.MyProto.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasStr()) {
          bitField0_ |= 0x00000002;
          str_ = other.str_;
          onChanged();
        }
        if (other.hasI32()) {
          setI32(other.getI32());
        }
        if (other.hasI64()) {
          setI64(other.getI64());
        }
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.MyProtoOuterClass.MyProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.MyProtoOuterClass.MyProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int messageType_ = 1;
      /**
       * <code>optional .test.MyProto.MessageType message_type = 12;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .test.MyProto.MessageType message_type = 12;</code>
       */
      public test.MyProtoOuterClass.MyProto.MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        test.MyProtoOuterClass.MyProto.MessageType result = test.MyProtoOuterClass.MyProto.MessageType.valueOf(messageType_);
        return result == null ? test.MyProtoOuterClass.MyProto.MessageType.TYPE1 : result;
      }
      /**
       * <code>optional .test.MyProto.MessageType message_type = 12;</code>
       */
      public Builder setMessageType(test.MyProtoOuterClass.MyProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .test.MyProto.MessageType message_type = 12;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object str_ = "hello world";
      /**
       * <code>optional string str = 1 [default = "hello world"];</code>
       */
      public boolean hasStr() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string str = 1 [default = "hello world"];</code>
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            str_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str = 1 [default = "hello world"];</code>
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str = 1 [default = "hello world"];</code>
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str = 1 [default = "hello world"];</code>
       */
      public Builder clearStr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str = 1 [default = "hello world"];</code>
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        str_ = value;
        onChanged();
        return this;
      }

      private int i32_ ;
      /**
       * <code>optional int32 i32 = 2;</code>
       */
      public boolean hasI32() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 i32 = 2;</code>
       */
      public int getI32() {
        return i32_;
      }
      /**
       * <code>optional int32 i32 = 2;</code>
       */
      public Builder setI32(int value) {
        bitField0_ |= 0x00000004;
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 i32 = 2;</code>
       */
      public Builder clearI32() {
        bitField0_ = (bitField0_ & ~0x00000004);
        i32_ = 0;
        onChanged();
        return this;
      }

      private long i64_ ;
      /**
       * <code>optional int64 i64 = 3;</code>
       */
      public boolean hasI64() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 i64 = 3;</code>
       */
      public long getI64() {
        return i64_;
      }
      /**
       * <code>optional int64 i64 = 3;</code>
       */
      public Builder setI64(long value) {
        bitField0_ |= 0x00000008;
        i64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 i64 = 3;</code>
       */
      public Builder clearI64() {
        bitField0_ = (bitField0_ & ~0x00000008);
        i64_ = 0L;
        onChanged();
        return this;
      }

      private test.MyProtoOuterClass.MyType msg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          test.MyProtoOuterClass.MyType, test.MyProtoOuterClass.MyType.Builder, test.MyProtoOuterClass.MyTypeOrBuilder> msgBuilder_;
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      public test.MyProtoOuterClass.MyType getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? test.MyProtoOuterClass.MyType.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      public Builder setMsg(test.MyProtoOuterClass.MyType value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      public Builder setMsg(
          test.MyProtoOuterClass.MyType.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      public Builder mergeMsg(test.MyProtoOuterClass.MyType value) {
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              msg_ != null &&
              msg_ != test.MyProtoOuterClass.MyType.getDefaultInstance()) {
            msg_ =
              test.MyProtoOuterClass.MyType.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      public test.MyProtoOuterClass.MyType.Builder getMsgBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      public test.MyProtoOuterClass.MyTypeOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              test.MyProtoOuterClass.MyType.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>optional .test.MyType msg = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          test.MyProtoOuterClass.MyType, test.MyProtoOuterClass.MyType.Builder, test.MyProtoOuterClass.MyTypeOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              test.MyProtoOuterClass.MyType, test.MyProtoOuterClass.MyType.Builder, test.MyProtoOuterClass.MyTypeOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.MyProto)
    }

    // @@protoc_insertion_point(class_scope:test.MyProto)
    private static final test.MyProtoOuterClass.MyProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.MyProtoOuterClass.MyProto();
    }

    public static test.MyProtoOuterClass.MyProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyProto>
        PARSER = new com.google.protobuf.AbstractParser<MyProto>() {
      @java.lang.Override
      public MyProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.MyProtoOuterClass.MyProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_MyType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_MyType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_MyProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_MyProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMyProto.proto\022\004test\"\025\n\006MyType\022\013\n\003i32\030\001" +
      " \001(\005\"\256\001\n\007MyProto\022/\n\014message_type\030\014 \001(\0162\031" +
      ".test.MyProto.MessageType\022\030\n\003str\030\001 \001(\t:\013" +
      "hello world\022\013\n\003i32\030\002 \001(\005\022\013\n\003i64\030\003 \001(\003\022\031\n" +
      "\003msg\030\004 \001(\0132\014.test.MyType\"#\n\013MessageType\022" +
      "\t\n\005TYPE1\020\001\022\t\n\005TYPE2\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_MyType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_MyType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_MyType_descriptor,
        new java.lang.String[] { "I32", });
    internal_static_test_MyProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_MyProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_MyProto_descriptor,
        new java.lang.String[] { "MessageType", "Str", "I32", "I64", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
